### PR TITLE
Add Download and point directly to Documentation

### PR DESCRIPTION
**Pull request by hishamhm**
These were the two most important pages from the old website, and all other pages are reachable from these two.

### CODE REVIEW

**Comment by leafo** [comment]
We're running out of space on the header:

**Comment by hishamhm** [comment]
Oh.

How about

Download . Docs . Person Person . <b>Upload</b> . Settings . Log Out

?

**Comment by leafo** [comment]
Works for me, will probably have to redo the header links at some point though.

**Comment by hishamhm** [comment]
Thanks! 

> Works for me, will probably have to redo the header links at some point though.

Agreed! (Especially since I'd also like to fit the logo in there at some point :) )

**Pull request merged**
